name : Reloading images and movies
on :
  workflow_dispatch:
    
jobs:
  image_confirm:
    runs-on: ubuntu-latest
    steps:
    - name: check out repository
      uses: actions/checkout@v1
    
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: requirements
      run: |
        pip install requests
        pip install tqdm
        pip install argparse
    
    - name: img_reload
      run: |
          python img_confirm.py
          python img_reload.py --d True --e True
    
    - name: mov_reload
      run: |
          python mov_reload.py --d True

    - name: Remote Time
      id : time
      uses: Plabick/Remote-Time-Action@1.01
      with:
        timezone: utc+08

    - name: git_add
      run: |
        git config --global user.email 1978633500@qq.com
        git config --global user.name kaleidoscope
        git add .
        git commit -m "Reloaded_${{steps.time.outputs.dateTime}}" -a
     
    - name: git_push
      uses: ad-m/github-push-action@master
      with: 
        github_token: ${{secrets.ACCESS_TOKEN}}
 
